config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, controllers: { sessions: 'users/sessions' },
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout }


  resources :badges, only: :index
  get 'show_all', to: 'badges#show_all'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :text, presence: true
  validate :validate_answers_number, on: :create

  scope :correct_answers, -> { where(correct: true) }

  private

  def validate_answers_number
    return if question.answers.count < 4

    errors.add(:question_id, 'Not a valid number of answers per question')
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :delete_all
  has_many :users, through: :user_badges

  before_save :set_image_if_blank

  validates :title, presence: true
  validates :rule, presence: true

  BADGES_NAMES = { 'С первой попытки' => :test_first_try, 'Все тесты категории' => :all_tests_category, 'Все тесты уровня' => :all_tests_level }.freeze

  private

  def set_image_if_blank
    self.image = '../../badge.png' if image.blank?
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :question

  validates :gist_url, presence: true

  def gist_hash
    gist_url.split('/').last
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, optional: true
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :text, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :author, class_name: 'User', foreign_key: :author_id, optional: true
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy, -> { where(level: 0..1) }
  scope :normal, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :level, ->(level) { where(level: level) }
  scope :with_category, ->(category_name) { joins(:category).where(categories: { title: category_name }).order(title: :desc) }

  def self.test_list
    with_category.pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_PASSAGE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def number_of_questions
    test.questions.count
  end

  def progress
    test.questions.index(current_question) + 1
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def completed?
    current_question.nil?
  end

  def passed_successfully?
    success_rate >= SUCCESS_PASSAGE
  end

  def success_rate
    ((correct_questions * 100) / test.questions.count.to_f)
  end

  private

  def next_question
    if new_record?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers_count = right_answers.count
    (correct_answers_count == right_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def right_answers
    current_question.answers.correct_answers
  end

  def before_validation_set_current_question
    self.current_question = next_question
  end
end

app/models/tests_user.rb
# frozen_string_literal: true

class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_FORMAT = /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: :author_id, dependent: :nullify
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :delete_all
  has_many :badges, through: :user_badges

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :confirmable

  def tests_passed(level)
    tests.where(tests: { level: level })
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def successful_tests
    self.test_passages.where(current_question: nil).select(&:passed_successfully?)
  end

  def admin?
    is_a?(Admin)
  end

  def to_s
    full_name = first_name.to_s
    full_name += " #{last_name}" if last_name.to_s.present?
    full_name += " (#{name})" if full_name.to_s.present? && name.to_s.present?
    full_name = name if full_name.to_s.empty?
    full_name = email if full_name.to_s.empty?
    full_name
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
  end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:text, :correct)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ActionController::Base

  def index
    @badges = current_user.badges
  end

  def show_all
    @all_badges = Badge.all
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: :start

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to block_given? ? yield : repo, "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def flash_messages
    flash.map do |key, message|
      content_tag :p, message, class: "flash #{key}"
    end.join.html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    action_title = question.new_record? ? 'Create new' : 'Edit'
    action_title << " #{question.test.title} Question"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/admin/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'Test Guru', admin_tests_path, class: 'navbar-brand' %>
  <%= link_to 'Gist', admin_gists_path, class: 'nav-link'%>
  <%= link_to 'Badges', admin_badges_path, class: 'nav-link'%>
  <span class="navbar-text">

      Welcome, <b class="nav-admin user-email"><%= current_user.email %></b>  Guru |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
     </span>
</nav>

app/views/layouts/_footer.html.erb
<div class="mt-3 ml-3">
  <p>Author: Dmarmy </p>
  <%= github_url('Dmarmy', 'test-guru') { 'Test Guru on GitHub' } %>
 <p>Study project from online school <a href="http://www.thinknetica.com/" target="_blank">Thinknetica</a></p>
  <p><%= current_year %></p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar">
    <h2><%= link_to "Test-Guru", root_path %></h2>

  <span class="navbar-text">

    <% if user_signed_in? %>
      Welcome, <b><%= current_user.email %></b> Guru |
      <%= link_to 'Badges', badges_path, class: 'badge badge-primary' %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'badge badge-primary' %>
    <% else %>
      <%= link_to 'Signup', new_user_registration_path, class: 'badge badge-primary' %>
      <%= link_to 'Login',  new_user_session_path, class: 'badge badge-primary' %>
    <% end %>

  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Panel | TestGuru</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'admin/header' %>
<%= flash_messages %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= flash_messages %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>