config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, controllers: { sessions: 'users/sessions' },
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout }


  resources :badges, only: :index
  get 'show_all', to: 'badges#show_all'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :delete_all
  has_many :users, through: :user_badges

  before_save :set_image_if_blank

  validates :title, presence: true
  validates :rule, presence: true

  BADGES_NAMES = { 'С первой попытки' => :test_first_try, 'Все тесты категории' => :all_tests_category, 'Все тесты уровня' => :all_tests_level }.freeze

  private

  def set_image_if_blank
    self.image = '../../badge.png' if image.blank?
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show update edit destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :rule, :image)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ActionController::Base

  def index
    @badges = current_user.badges
  end

  def show_all
    @all_badges = Badge.all
  end
end

app/views/badges/_all_badges.html.erb
<tr>
  <td class="align-middle"><img src=<%="#{badge.image}"%> height="60"></td>
  <td class="align-middle"><%= Badge::BADGES_NAMES.key(badge.title.to_sym) + " #{badge.rule}" %></td>
</tr>

app/views/badges/_badge.html.erb
<tr>
  <td class="align-middle"><img src=<%="#{badge.image}"%> height="60"></td>
  <td class="align-middle"><%= Badge::BADGES_NAMES.key(badge.title.to_sym) + " #{badge.rule}" %></td>
</tr>

app/views/badges/index.html.erb
<div class="container">
  <div class="mt-3">
    <% if @badges.blank? %>
      <h3> You dont have any badges yet </h3>
    <% else %>
      <%= render @badges %>
    <% end %>
  </div>
  <div class="mt-3">
    <%= link_to 'Available badges', show_all_path %>
  </div>
</div>

app/views/badges/show_all.html.erb
<h1 class="text-center font-weight-normal"> Badges </h1>
<div class="mt-3">

  <table class="table table-hover table-bordered">
    <tr class="table-primary">
      <th> Icon </th>
      <th> Rule </th>
    </tr>

    <%= render @badges %>
  </table>
  <p>
    <%= link_to 'back', badges_path %>
  </p>
</div>