config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, controllers: { sessions: 'users/sessions' },
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout }


  resources :badges, only: :index
  get 'show_all', to: 'badges#show_all'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :question

  validates :gist_url, presence: true

  def gist_hash
    gist_url.split('/').last
  end
end

app/controllers/admin/gists_controller.rb
class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.all
  end
end

app/views/admin/gists/_gist.html.erb
<tr>
  <td><%= link_to gist.question.text.truncate(25), admin_question_path(gist.question) %></td>
  <td><%= link_to gist.gist_hash, gist.gist_url, target: :blank %></td>
  <td><%= gist.user.email %></td>
</tr>

app/views/admin/gists/index.html.erb
<h1>Gists list</h1>
<table>
  <tr>
    <th>Gist question</th>
    <th>Gist URL</th>
    <th>User </th>
  </tr>

  <%= render @gists %>

</table>
<%= link_to 'Back', admin_tests_path %>