config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, controllers: { sessions: 'users/sessions' },
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout }


  resources :badges, only: :index
  get 'show_all', to: 'badges#show_all'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, optional: true
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :text, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_PASSAGE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def number_of_questions
    test.questions.count
  end

  def progress
    test.questions.index(current_question) + 1
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def completed?
    current_question.nil?
  end

  def passed_successfully?
    success_rate >= SUCCESS_PASSAGE
  end

  def success_rate
    ((correct_questions * 100) / test.questions.count.to_f)
  end

  private

  def next_question
    if new_record?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers_count = right_answers.count
    (correct_answers_count == right_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def right_answers
    current_question.answers.correct_answers
  end

  def before_validation_set_current_question
    self.current_question = next_question
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      BadgeService.new(@test_passage).call
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.success?
      Gist.create!(question: @test_passage.current_question, user: @test_passage.user, gist_url: result.html_url)
      flash[:notice] = "#{t('.success')} #{view_context.link_to(t('.view_gist'), result.html_url, target: :blank)}"
    else
      flash[:alert] = t('.failure')
    end

    redirect_to @test_passage
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
 <h1> Result: </h1>
 <% if @test_passage.passed_successfully? %>
   <p>Congrats! You passed the <%= @test_passage.test.title %>. Success rate: <span class="success"><%= @test_passage.success_rate.round %> %</span></p>
 <% else %>
   <p>You failed the <%= @test_passage.test.title %>. Success rate: <span class="fail"><%= @test_passage.success_rate.round %> %</span></p>
 <% end %>

 <%= link_to 'All tests', tests_path %>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> </h1>
<%= content_tag :div, class: 'passage-progress', data: {questions_amount: @test_passage.number_of_questions} do %>
  <%= content_tag :div, class: 'progress-bar', data: {question: @test_passage.progress} do %>
  <% end %>
<% end %>

<p>
  <b><%= @test_passage.current_question.text %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :text, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object_id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit 'Next' %></p>
  <p>Question <%= @test_passage.current_question_number %> of <%= @test_passage.number_of_questions %></p>



<% end %>